language: cpp
compiler: gcc
dist: trusty
sudo: required
cache:
    directories:
        - apt_mingw_cache
        - $HOME/.ccache
matrix:
    include:
        - env: QT5=True TARGET_OS=win64
before_install:
   - . ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}.before_install.sh
install:
    - . ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}.install.sh
before_script:
    - mkdir build && cd build
    - export CMAKE_FLAGS="-DWANT_QT5=$QT5 -DUSE_WERROR=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo"
    - if [ -z "$TRAVIS_TAG" ]; then export CMAKE_FLAGS="$CMAKE_FLAGS -DUSE_CCACHE=ON"; fi
script:
    - . ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}.script.sh
    - make -j4
    - if [[ $TARGET_OS != win* ]]; then make tests && ./tests/tests; fi;
after_script:
    - ccache -s
before_deploy: make package
deploy:
    provider: releases
    api_key: 
        secure: D6JuAVRildE+f++/ErWBi/7lUyqINUfjPHsFRH4xki9JNOcT7Cn5qveM1BnT16sMmj1Ep3GXvtOFDpX19QRpv6tFR9cVa7sHc/3AvcuGYRmhHtdjgLv7Jblug1zNnGAOGpEpnAtxNd6D0UCTPQX1OJFjNvQpmAL8T0VZwtEaxMPDtzh0R+2YcJ6lcSj7rZzzoUqDZN8aKM7dAoXqCRF4Fx8aqBO5yMj89gh1nEN/78AyAGmoRSIdC7haQXIMNcW1yVSvkWI7dEiykfyuBzckXHF9naSMRvFh5r8p68dnbFQT34E4yaTBMn/Dt2I9tAqn8eE0Q160iqlDd8LLw48vSlJRxhl/ur3wFeJjxaWjcWn6OUyjdC0wnpg3ymhxTZdbWRItuYiqcQ8cVV6kvr0MFJBGQJ98mmEJtUti8A5ZQNPkX0qKrQR+AkIZMMKBstdLWDFGXoWxEAztKeO8T0gMPzG/OQwWEI81c7Zc92kfQvGwuhyRe4kj/T4UvmXrLwlJYvMHIEnz6x/chDX3NzuCEi5zjx1HK7j3UT1kofgq3H2ZpMKUwbSB8/xTjtfF0myp8uL3x0Iy5td508YCC+DUnWRoumP4zTqDO4kXKWu7iQb7NJB54ebWHBNth3G/mjmj9RTKRhRupBQ5p1q9rGANzQ7IUxiUKPjVG/mJ++cMdGs=
    file: lmms-${TRAVIS_TAG:1}-$TARGET_OS-$QT5.exe
    skip_cleanup: true
    on:
        all_branches: true
        condition: '("$TARGET_OS" = win??)'
    repo: arebao/lmms
notifications:
    webhooks:
       urls:
           - https://webhooks.gitter.im/e/1ac7fc698195981a9227
       on_success: change  # options: [always|never|change] default: always
       on_failure: always  # options: [always|never|change] default: always
       on_start: never     # options: [always|never|change] default: always 
